### ISSUE TITLE
Failed on latest tag

### ISSUE THREAD

**Issue by adhiemsumitro** [voryx/WampPost#14]
I try to install the latest 0.2.0
but it gave me errors : 

> PHP Fatal error:  Uncaught InvalidArgumentException: Invalid URI "tcp://127.0.0.1" given in /home/andiadh/wamppost/vendor/react/socket/src/TcpServer.php:149
> 
> Stack trace:
> #0 /home/andiadh/wamppost/vendor/react/socket/src/Server.php(35): React\Socket\TcpServer->__construct('tcp://127.0.0.1', Object(React\EventLoop\StreamSelectLoop), Array)
> 
> #1 /home/andiadh/wamppost/vendor/voryx/wamppost/src/WampPost/WampPost.php(26): React\Socket\Server->__construct('127.0.0.1', Object(React\EventLoop\StreamSelectLoop))
> 
> #2 /home/andiadh/wamppost/wamppost.php(5): WampPost\WampPost->__construct('realm1', Object(React\EventLoop\StreamSelectLoop), '127.0.0.1', 8181)
> 
> #3 {main}
>   thrown in /home/andiadh/wamppost/vendor/react/socket/src/TcpServer.php on line 149
> 

I then revert downloading 0.1.5 and everything goes well
Please advice

**Comment by icorreacm** [comment]
If you are using the example in README, you must change line 13 to:

`$wp = new WampPost(WS_REALM, $router->getLoop(), 'tcp://127.0.0.1:8181');`

pass IP and PORT in one parameter

**Comment by icorreacm** [comment]
If you are using the example in README, you must change line 13 to:

`$wp = new WampPost(WS_REALM, $router->getLoop(), 'tcp://127.0.0.1:8181');`

pass IP and PORT in one parameter
